# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  scheme: 'DemoProject'
  sdk: 'iphoneos'
  configuration: 'Release'
  
steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: Certificates.p12
    certPwd: ios

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Apple Provisioning Profile'
  inputs:
    provProfileSecureFile: 'Sober_Development_Profile-2.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    packageApp: true
    archivePath: '$(build.artifactStagingDirectory)'
    exportPath: 'output/$(sdk)/$(configuration)'
#    exportOptions: 'specify'
#    exportMethod: 'development'
#   exportTeamId: '2R2S7RM348'
#   useXcpretty: true
#   publishJUnitResults: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.app'
    targetFolder: '$(build.artifactStagingDirectory)'    
- task: PublishBuildArtifacts@1